# Azure Pipeline for running Scylla CLI validation task
# This pipeline runs the proxy validation CLI on a schedule

name: Scylla-CLI-Validation

trigger: none

pr: none

schedules:
    - cron: '*/30 * * * *'
      displayName: 'Run validation every 5 minutes'
      branches:
          include:
              - main
              - master
      always: true

pool:
    vmImage: 'ubuntu-latest'

variables:
    - name: pythonVersion
      value: '3.11'
    - name: workingDirectory
      value: '$(System.DefaultWorkingDirectory)'

stages:
    - stage: Validate
      displayName: 'Proxy Validation Stage'
      jobs:
          - job: RunCLI
            displayName: 'Run Validation CLI'
            timeoutInMinutes: 30

            steps:
                - checkout: self
                  displayName: 'Checkout repository'
                  clean: true

                - task: UsePythonVersion@0
                  displayName: 'Use Python $(pythonVersion)'
                  inputs:
                      versionSpec: '$(pythonVersion)'
                      addToPath: true
                      architecture: 'x64'

                - script: |
                      python --version
                      pip --version
                  displayName: 'Display Python version'

                - script: |
                      python -m pip install --upgrade pip setuptools wheel
                      pip install -r requirements.txt
                  displayName: 'Install Python dependencies'
                  workingDirectory: '$(workingDirectory)'

                - script: |
                      echo "Starting proxy validation..."
                      python cli.py
                  displayName: 'Execute validation CLI'
                  workingDirectory: '$(workingDirectory)'
                  env:
                      # Database configuration
                      DB_URL: $(DB_URL)
                      VALIDATE_BATCH_LIMIT: 1000

                  continueOnError: true
