# main:
#   "crontab: */10 * * * *":
#     - name: Validate proxies
#       runner:
#         cpus: 2
#       docker:
#         image: docker.cnb.cool/oxzk.co/code-server:latest
#       imports: https://cnb.cool/oxzk.co/env/-/blob/main/scylla.json
#       stages:
#         - name: Set up Python venv
#           env:
#             VALIDATE_BATCH_LIMIT: 400
#           script: |
#             pwd
#             ls -la
#             cd /workspace
#             if [ ! -d ".venv" ]; then
#               python3 -m venv .venv
#             fi
#             . .venv/bin/activate

#             pip install -r requirements.txt

#             python cli.py

#             rm -rf /workspace/.venv

# main:
#   push:
#     - runner:
#         cpus: 2
#       docker:
#         image: docker.cnb.cool/oxzk.co/code-server:latest
#       imports: https://cnb.cool/oxzk.co/env/-/blob/main/v2ray.json
#       stages:
#         - name: python
#           script: |
#             ls -la
#             nohup v2ray -c /root/.cnb/v2ray-config.json >/dev/null 2>&1 &

$:
  vscode:
    - runner:
        cpus: 4
        # tags: cnb:arch:amd64:gpu
      docker:
        image: docker.cnb.cool/oxzk.co/code-server:latest
      services:
        - vscode
        - docker
      stages:
        - name: cnb-init
          script: |
            bash /root/.cnb/cnb-init.sh
      endStages:
        - name: cnb-end
          script: |
            bash /root/.cnb/cnb-destory.sh